language: java
install: true
cache:
  directories:
    - $HOME/.m2

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      services:
        - xvfb
      jdk:
        - openjdk11

script:
  - sh setup.sh
  - mvn -Pbuild-eclipse clean verify
  - echo "done"
