language: java
install: true
os: linux
dist: bionic
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
services:
  - xvfb

script:
  - sh setup.sh
  # This skips tests because tests hang on travis (but not locally) this will be replaced with
  # CodeBuild in the future so it at least gives us something
  - mvn -DskipTests -Pbuild-eclipse clean verify

branches:
  only:
  - master
  - /^feature\/.*$/
